<a href="https://colab.research.google.com/github/Evertonvcf/Exerc-cios_DataFrame/blob/main/exercicio_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
x = np.array([1, 2.5, 7, -78,-0.9, 130, 25])

In [4]:
x

array([  1. ,   2.5,   7. , -78. ,  -0.9, 130. ,  25. ])

In [5]:
# cria um variavel y com uma lista de 1 a 10
y = np.arange(1,11)

In [6]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
vetor = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [8]:
vetor

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
vetor2 = np.ones((2,5))

In [10]:
vetor2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
dados_seq = np.arange(1, 101, 3)

In [12]:
dados_seq

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [13]:
raiz = np.sqrt(dados_seq)

In [14]:
raiz

array([ 1.        ,  2.        ,  2.64575131,  3.16227766,  3.60555128,
        4.        ,  4.35889894,  4.69041576,  5.        ,  5.29150262,
        5.56776436,  5.83095189,  6.08276253,  6.32455532,  6.55743852,
        6.78232998,  7.        ,  7.21110255,  7.41619849,  7.61577311,
        7.81024968,  8.        ,  8.18535277,  8.36660027,  8.54400375,
        8.71779789,  8.88819442,  9.05538514,  9.21954446,  9.38083152,
        9.53939201,  9.69535971,  9.8488578 , 10.        ])

In [15]:
dados_seq[9]*2

np.int64(56)

In [16]:
df = pd.DataFrame(dados_seq,columns=['Numeros'])
df['Raiz']=raiz

In [17]:
df

Numeros       Raiz
0         1   1.000000
1         4   2.000000
2         7   2.645751
3        10   3.162278
4        13   3.605551
5        16   4.000000
6        19   4.358899
7        22   4.690416
8        25   5.000000
9        28   5.291503
10       31   5.567764
11       34   5.830952
12       37   6.082763
13       40   6.324555
14       43   6.557439
15       46   6.782330
16       49   7.000000
17       52   7.211103
18       55   7.416198
19       58   7.615773
20       61   7.810250
21       64   8.000000
22       67   8.185353
23       70   8.366600
24       73   8.544004
25       76   8.717798
26       79   8.888194
27       82   9.055385
28       85   9.219544
29       88   9.380832
30       91   9.539392
31       94   9.695360
32       97   9.848858
33      100  10.000000

In [18]:
dados={'Empresa':['Microsoft', 'Google', 'Univesp','NVData Analytics','Power Bi Experience', 'USP'],'Qtde func':[1000, 1500, 500, 100, 100, 499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https;//univesp.br/','https://vcdata.com.br','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft', '@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934],'Pais':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

In [19]:
df2 = pd.DataFrame(dados)

In [20]:
df2

Empresa  Qtde func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https;//univesp.br/   
3     NVData Analytics        100              https://vcdata.com.br   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    Pais  
0       @microsoft     1975     EUA  
1          @google     1998     EUA  
2  @univespoficial     2012  Brasil  
3         @nv_data     2019  Brasil  
4        @leokarpa     2016  Brasil  
5     @usp.oficial     1934  Brasil

In [21]:
df2.head(3)

Empresa  Qtde func                             Site        Instagram  \
0  Microsoft       1000  https://www.microsoft.com/pt-br       @microsoft   
1     Google       1500          https://www.google.com/          @google   
2    Univesp        500              https;//univesp.br/  @univespoficial   

   Criação    Pais  
0     1975     EUA  
1     1998     EUA  
2     2012  Brasil

In [22]:
df2.tail(3)

Empresa  Qtde func                               Site  \
3     NVData Analytics        100              https://vcdata.com.br   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

      Instagram  Criação    Pais  
3      @nv_data     2019  Brasil  
4     @leokarpa     2016  Brasil  
5  @usp.oficial     1934  Brasil

In [23]:
df2.Criação>=2015

0    False
1    False
2    False
3     True
4     True
5    False
Name: Criação, dtype: bool

In [24]:
df2['Chefes']= df2['Qtde func']/23

In [25]:
df2

Empresa  Qtde func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https;//univesp.br/   
3     NVData Analytics        100              https://vcdata.com.br   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    Pais     Chefes  
0       @microsoft     1975     EUA  43.478261  
1          @google     1998     EUA  65.217391  
2  @univespoficial     2012  Brasil  21.739130  
3         @nv_data     2019  Brasil   4.347826  
4        @leokarpa     2016  Brasil   4.347826  
5     @usp.oficial     1934  Brasil  21.695652